"""initial schema：與導入 Alembic 前 create_all 建立的結構相同

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 05:54:29.333384
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_prices',
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('stock_id', 'date')
    )
    op.create_table('indicators',
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ma5', sa.Float(), nullable=True),
    sa.Column('ma20', sa.Float(), nullable=True),
    sa.Column('ma60', sa.Float(), nullable=True),
    sa.Column('rsi14', sa.Float(), nullable=True),
    sa.Column('k', sa.Float(), nullable=True),
    sa.Column('d', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_hist', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('stock_id', 'date')
    )
    op.create_table('monthly_revenue',
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('stock_id', 'year', 'month')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('link', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'link', name='uq_news_stock_link')
    )
    op.create_index('ix_news_stock_id', 'news', ['stock_id'], unique=False)

    op.create_table('reports',
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=False),
    sa.Column('risks', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('stock_id', 'date')
    )
    op.create_table('stocks',
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_table('watchlist',
    sa.Column('chat_id', sa.String(length=30), nullable=False),
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', 'stock_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    op.drop_table('stocks')
    op.drop_table('reports')
    op.drop_index('ix_news_stock_id', table_name='news')

    op.drop_table('news')
    op.drop_table('monthly_revenue')
    op.drop_table('indicators')
    op.drop_table('daily_prices')
    # ### end Alembic commands ###
